"""
OpenAI service for marketing kit generation.

This module communicates with the OpenAI API to generate marketing assets
for music producers based on beat metadata and audio analysis results.
"""

import os

from dotenv import load_dotenv
from openai import OpenAI

from app.schemas.marketing import BeatInfo, MarketingKit

load_dotenv()

# Initialize the OpenAI client using the API key stored in environment variables.
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def generate_marketing_kit_with_ai(beat: BeatInfo) -> MarketingKit:
    """
    Generate a complete marketing kit for a beat using OpenAI.

    The generated marketing kit includes:
    - Searchable beat tags
    - YouTube titles
    - BeatStars description
    - Artist matches
    - Social media caption
    - Cover art prompt

    Returns:
        MarketingKit: Structured marketing assets generated by the AI model.
    """
    duration_formatted = "Unknown"

    # Convert the beat duration into a human-readable format for the prompt.
    if beat.duration_seconds:
        minutes = int(beat.duration_seconds // 60)
        seconds = int(beat.duration_seconds % 60)
        duration_formatted = f"{minutes}:{seconds:02d}"

    response = client.responses.parse(
        model="gpt-4o-mini",
        input=[
            {
                "role": "system",
                "content": (
                    "You are an expert music marketing assistant for online beat producers. "
                    "Generate polished, practical marketing assets for YouTube, BeatStars, "
                    "and social media."
                ),
            },
            {
                "role": "user",
                "content": f"""
Generate a marketing kit for this beat.

Beat title: {beat.title}
Genre: {beat.genre}
Mood: {beat.mood}
BPM: {beat.bpm}
Key: {beat.key}
Duration: {duration_formatted}
Energy: {beat.energy}

Requirements:
- Create 8-12 searchable beat tags.
- Create 3 YouTube-ready titles.
- Create a BeatStars-style description.
- Give 3-5 artist matches.
- Create 1 short social media caption.
- Create 1 detailed cover art prompt.
- Keep everything specific to the beat info.
""",
            },
        ],
        # Parse the model output directly into the MarketingKit schema.
        text_format=MarketingKit,
    )

    return response.output_parsed